export const CHECK_EMAILVALIDITY_REQUEST = 'CHECK_EMAILVALIDITY_REQUEST'
export const CHECK_EMAILVALIDITY_SUCCESS = 'CHECK_EMAILVALIDITY_SUCCESS'
export const CHECK_EMAILVALIDITY_FAILURE = 'CHECK_EMAILVALIDITY_FAILURE'

function checkEmail (params) {
  return {
    type: CHECK_EMAILVALIDITY_REQUEST,
    ...params
  }
}

export {
  checkEmail
}
