export const GET_EXPEDITION_REQUEST = 'GET_EXPEDITION_REQUEST'
export const GET_EXPEDITION_SUCCESS = 'GET_EXPEDITION_SUCCESS'
export const GET_EXPEDITION_FAILURE = 'GET_EXPEDITION_FAILURE'

export const GET_EXPEDITIONSERVICES_REQUEST = 'GET_EXPEDITIONSERVICES_REQUEST'
export const GET_EXPEDITIONSERVICES_SUCCESS = 'GET_EXPEDITIONSERVICES_SUCCESS'
export const GET_EXPEDITIONSERVICES_FAILURE = 'GET_EXPEDITIONSERVICES_FAILURE'

export const GET_SHIPPINGCHARGE_REQUEST = 'GET_SHIPPINGCHARGE_REQUEST'
export const GET_SHIPPINGCHARGE_SUCCESS = 'GET_SHIPPINGCHARGE_SUCCESS'
export const GET_SHIPPINGCHARGE_FAILURE = 'GET_SHIPPINGCHARGE_FAILURE'

function getExpedition () {
  return {
    type: GET_EXPEDITION_REQUEST
  }
}

function getServices () {
  return {
    type: GET_EXPEDITIONSERVICES_REQUEST
  }
}

function getShippingCharge (params) {
  return {
    type: GET_SHIPPINGCHARGE_REQUEST,
    ...params
  }
}

export {
  getExpedition,
  getServices,
  getShippingCharge
}
