import AppConfig from '../Config/AppConfig.example'

const images = {
  about: `https://skyshi.com/sites/skyshi.com/files/logo_rev_1.png`,
  password: `${AppConfig.baseURL}static/images/password.svg`,
  phoneSuccess: `${AppConfig.baseURL}static/images/phone.png`,
  phoneAccount: `${AppConfig.baseURL}static/images/phone-account.svg`,
  regSuccess: `${AppConfig.baseURL}static/images/reg-success.svg`,
  user: `${AppConfig.baseURL}static/images/pict.jpg`,
  banner: `${AppConfig.baseURL}static/images/banner.jpg`,
  thumb: `${AppConfig.baseURL}static/images/thumb.jpg`,
  noImage: `${AppConfig.baseURL}static/images/imagenotfound.svg`,
  loading: `${AppConfig.baseURL}static/images/loading.png`,
  loadingFailed: `${AppConfig.baseURL}static/images/loading-failed.png`,
  startDisabled: `${AppConfig.baseURL}static/images/komuto-icon/050_star-grey.svg`,
  startEnabled: `${AppConfig.baseURL}static/images/komuto-icon/051_star_yellow.svg`,
  unverifiedPhone: `${AppConfig.baseURL}static/images/ilustrasi-no-hp-belum-verifikasi.png`,
  verifiedPhone: `${AppConfig.baseURL}static/images/ilustrasi-no-hp-sudah-verifikasi.png`,
  iconCamera: `${AppConfig.baseURL}static/images/icon-kamera.svg`,
  jne: `${AppConfig.baseURL}static/images/jne.png`,
  pos: `${AppConfig.baseURL}static/images/pos.png`,
  hasOpenedStore: `${AppConfig.baseURL}static/images/icon-berhasil-membuka-toko.png`,
  alfamart: `${AppConfig.baseURL}static/images/alfamart.png`,
  alfamidi: `${AppConfig.baseURL}static/images/alfamidi.png`,
  alto: `${AppConfig.baseURL}static/images/alto.png`,
  atmBersama: `${AppConfig.baseURL}static/images/atmbersama.png`,
  bca: `${AppConfig.baseURL}static/images/bca.png`,
  bri: `${AppConfig.baseURL}static/images/bri.png`,
  bni: `${AppConfig.baseURL}static/images/bni.png`,
  dokuWallet: `${AppConfig.baseURL}static/images/doku-wallet.png`,
  epayBri: `${AppConfig.baseURL}static/images/epay-bri.png`,
  mandiriClickpay: `${AppConfig.baseURL}static/images/mandiri-clickpay.png`,
  mandiri: `${AppConfig.baseURL}static/images/mandiri.png`,
  masterCard: `${AppConfig.baseURL}static/images/mastercard.png`,
  mcSc: `${AppConfig.baseURL}static/images/mc-sc.png`,
  norton: `${AppConfig.baseURL}static/images/norton.png`,
  prima: `${AppConfig.baseURL}static/images/prima.png`,
  tiki: `${AppConfig.baseURL}static/images/tiki.png`,
  vByVisa: `${AppConfig.baseURL}static/images/v-by-visa.png`,
  visa: `${AppConfig.baseURL}static/images/visa.png`,
  transaksiDetail: `${AppConfig.baseURL}static/images/transaksi-detail.png`,
  notFound: `${AppConfig.baseURL}static/images/404.svg`,
  paymentSuccess: `${AppConfig.baseURL}static/images/payment-success.png`,
  paymentDone: `${AppConfig.baseURL}static/images/icon-payment-done.svg`,
  paymentExpired: `${AppConfig.baseURL}static/images/icon-payment-expired.svg`,
  paymentWaiting: `${AppConfig.baseURL}static/images/icon-payment-waiting-payment.svg`,
  paymentVerification: `${AppConfig.baseURL}static/images/icon-payment-waiting-verification.svg`,
  emptyStatesMessage: `${AppConfig.baseURL}static/images/empty-states-percakapan.svg`,
  emptyStatesDiscussion: `${AppConfig.baseURL}static/images/empty-states.svg`,
  review: `${AppConfig.baseURL}static/images/review.svg`,
  emptyStatesResolusi: `${AppConfig.baseURL}static/images/empty-states-resolusi.svg`,
  emptyStates: `${AppConfig.baseURL}static/images/empty-states.svg`,
  listProduct: `${AppConfig.baseURL}static/images/icon-daftar-produk.svg`,
  IconInfoBlue: `${AppConfig.baseURL}static/images/icon-info-blue.svg`,
  IconInfoYellow: `${AppConfig.baseURL}static/images/icon-info-yellow.svg`
}

export default images
