import AppConfig from '../Config/AppConfig'

const images = {
  about: `https://skyshi.com/sites/skyshi.com/files/logo_rev_1.png`,
  password: `${AppConfig.baseURL}static/images/password.svg`,
  phoneSuccess: `${AppConfig.baseURL}static/images/phone.png`,
  phoneAccount: `${AppConfig.baseURL}static/images/phone-account.svg`,
  regSuccess: `${AppConfig.baseURL}static/images/reg-success.svg`,
  user: `${AppConfig.baseURL}static/images/pict.jpg`,
  banner: `${AppConfig.baseURL}static/images/banner.jpg`,
  thumb: `${AppConfig.baseURL}static/images/thumb.jpg`,
  loading: `${AppConfig.baseURL}static/images/loading.gif`,
  loadingFailed: `${AppConfig.baseURL}static/images/loading-failed.jpg`,
  startDisabled: `${AppConfig.baseURL}static/images/komuto-icon/050_star-grey.svg`,
  startEnabled: `${AppConfig.baseURL}static/images/komuto-icon/051_star_yellow.svg`,
  unverifiedPhone: `${AppConfig.baseURL}static/images/ilustrasi-no-hp-belum-verifikasi.png`,
  verifiedPhone: `${AppConfig.baseURL}static/images/ilustrasi-no-hp-sudah-verifikasi.png`,
  iconCamera: `${AppConfig.baseURL}static/images/icon-kamera.svg`,
  hasOpenedStore: `${AppConfig.baseURL}static/images/icon-berhasil-membuka-toko.png`,
  transaksiDetail: `${AppConfig.baseURL}static/images/transaksi-detail.png`,
  notFound: `${AppConfig.baseURL}static/images/404.svg`,
  paymentSuccess: `${AppConfig.baseURL}static/images/payment-success.png`,
  paymentDone: `${AppConfig.baseURL}static/images/icon-payment-done.svg`,
  paymentExpired: `${AppConfig.baseURL}static/images/icon-payment-expired.svg`,
  paymentWaiting: `${AppConfig.baseURL}static/images/icon-payment-waiting-payment.svg`,
  paymentVerification: `${AppConfig.baseURL}static/images/icon-payment-waiting-verification.svg`,
  emptyStatesMessage: `${AppConfig.baseURL}static/images/empty-states-percakapan.svg`,
  emptyStatesDiscussion: `${AppConfig.baseURL}static/images/empty-states.svg`,
  review: `${AppConfig.baseURL}static/images/review.svg`,
  emptyStatesResolusi: `${AppConfig.baseURL}static/images/empty-states-resolusi.svg`,
  emptyStates: `${AppConfig.baseURL}static/images/empty-states.svg`,
  listProduct: `${AppConfig.baseURL}static/images/icon-daftar-produk.svg`,
  IconInfoBlue: `${AppConfig.baseURL}static/images/icon-info-blue.svg`,
  IconInfoYellow: `${AppConfig.baseURL}static/images/icon-info-yellow.svg`,
  wishlistEmpty: `${AppConfig.baseURL}static/images/wishlist-empty.svg`,
  cart: `${AppConfig.baseURL}static/images/cart.svg`,
  emptySelling: `${AppConfig.baseURL}static/images/empty-selling.svg`,
  emptyComplaint: `${AppConfig.baseURL}static/images/empty-complaint.svg`,
  emptyConfirmation: `${AppConfig.baseURL}static/images/empty-confirmation.svg`,
  emptyStateNewOrder: `${AppConfig.baseURL}static/images/empty-state-new-order.svg`,
  emptyDropshipping: `${AppConfig.baseURL}static/images/empty-dropshipping.svg`
}

export default images
