const images = {
  about: 'https://skyshi.com/sites/skyshi.com/files/logo_rev_1.png',
  password: '../../static/images/password.svg',
  phoneSuccess: '../../static/images/phone.png',
  phoneAccount: '../../static/images/phone-account.svg',
  regSuccess: '../../static/images/reg-success.svg',
  user: '../../static/images/pict.jpg',
  banner: '../../static/images/banner.jpg',
  thumb: '../../static/images/thumb.jpg',
  noImage: '../../static/images/imagenotfound.svg',
  loading: '../../static/images/loading.png',
  loadingFailed: '../../static/images/loading-failed.png',
  startDisabled: '../../static/images/komuto-icon/050_star-grey.svg',
  startEnabled: '../../static/images/komuto-icon/051_star_yellow.svg',
  unverifiedPhone: '../../static/images/ilustrasi-no-hp-belum-verifikasi.png',
  verifiedPhone: '../../static/images/ilustrasi-no-hp-sudah-verifikasi.png',
  iconCamera: '../../static/images/icon-kamera.svg',
  jne: '../../static/images/jne.png',
  pos: '../../static/images/pos.png',
  hasOpenedStore: '../../static/images/icon-berhasil-membuka-toko.png',
  alfamart: '../../static/images/alfamart.png',
  alfamidi: '../../static/images/alfamidi.png',
  alto: '../../static/images/alto.png',
  atmBersama: '../../static/images/atmbersama.png',
  bca: '../../static/images/bca.png',
  bri: '../../static/images/bri.png',
  bni: '../../static/images/bni.png',
  dokuWallet: '../../static/images/doku-wallet.png',
  epayBri: '../../static/images/epay-bri.png',
  mandiriClickpay: '../../static/images/mandiri-clickpay.png',
  mandiri: '../../static/images/mandiri.png',
  masterCard: '../../static/images/mastercard.png',
  mcSc: '../../static/images/mc-sc.png',
  norton: '../../static/images/norton.png',
  prima: '../../static/images/prima.png',
  tiki: '../../static/images/tiki.png',
  vByVisa: '../../static/images/v-by-visa.png',
  visa: '../../static/images/visa.png',
  transaksiDetail: '../../static/images/transaksi-detail.png',
  notFound: '../../static/images/404.svg',
  paymentSuccess: '../../static/images/payment-success.png'
}

export default images
